language: node_js
install:
- npm ci
cache:
  directories:
  - "$HOME/.npm"
jobs:
  include:
    - stage: test
      node_js: node
      script: jest --coverage --coverageReporters=text-lcov | coveralls
    - stage: build
      node_js: node
      script: webpack
