language: node_js
node_js: 10
install:
- npm ci
cache:
  directories:
  - "$HOME/.npm"
jobs:
  include:
  - stage: lint
    script: npm run lint
  - stage: test
    script: jest --coverage --coverageReporters=text-lcov | coveralls
  - stage: build
    script: npm run build
  - stage: release
    if: tag IS present
    deploy:
      provider: npm
      email: "$NPM_EMAIL"
      api_key: "$NPM_TOKEN"
      skip_cleanup: true
      on:
        tags: true
